books/urls.py
from django.urls import path
from books.views import CatalogListView, book_page

app_name = 'books'

urlpatterns = [
    path('', CatalogListView.as_view(), name='index'),
    path('<int:category_id>/', CatalogListView.as_view(), name='category_filter'),
    path('book/', book_page, name='book'),
]

booksharing/urls.py
from django.contrib import admin
from django.urls import path, include
from books.views import index
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name='index'),
    path('books/', include('books.urls', namespace='books')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

books/models.py
from django.db import models


class Category(models.Model):

    name = models.CharField(max_length=100, verbose_name='название')
    description = models.TextField(blank=True, verbose_name='описание')

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'

    def __str__(self):
        return self.name


class Theme(models.Model):

    name = models.CharField(max_length=100, verbose_name='название')
    description = models.TextField(blank=True, verbose_name='описание')

    class Meta:
        verbose_name = 'Тема'
        verbose_name_plural = 'Темы'

    def __str__(self):
        return self.name


class Publisher(models.Model):

    name = models.CharField(max_length=100, verbose_name='название')
    description = models.TextField(blank=True, verbose_name='описание')
    add_info = models.JSONField(blank=True, verbose_name='дополнительная информация')

    class Meta:
        verbose_name = 'Издательство'
        verbose_name_plural = 'Издательства'

    def __str__(self):
        return self.name


class Language(models.Model):

    name = models.CharField(max_length=100, verbose_name='название')

    class Meta:
        verbose_name = 'Язык'
        verbose_name_plural = 'Языки'

    def __str__(self):
        return self.name


class Author(models.Model):

    first_name = models.CharField(max_length=100, verbose_name='имя')
    last_name = models.CharField(max_length=100, verbose_name='фамилия')
    add_info = models.JSONField(blank=True, verbose_name='дополнительная информация')

    class Meta:
        verbose_name = 'Автор'
        verbose_name_plural = 'Авторы'

    def __str__(self):
        return self.full_name

    @property
    def full_name(self):
        return ' '.join([self.first_name, self.last_name])


class Book(models.Model):

    name = models.CharField(max_length=150, verbose_name='название')
    description = models.TextField(blank=True, verbose_name='описание')
    image = models.ImageField(upload_to='books_images', blank=True, null=True, verbose_name='обложка')
    isbn = models.CharField(max_length=20, blank=True, default='не имеет ISBN', verbose_name='ISBN')
    publish_year = models.PositiveIntegerField(default=1945, verbose_name='год публикации')
    pages_count = models.PositiveIntegerField(default=1, verbose_name='количество страниц')
    books_count = models.PositiveIntegerField(default=1, verbose_name='количество в наличии')
    publisher = models.ForeignKey(Publisher,
                                  on_delete=models.SET_NULL,
                                  null=True,
                                  related_name='books',
                                  verbose_name='издательство')
    category = models.ForeignKey(Category,
                                 on_delete=models.SET_NULL,
                                 null=True,
                                 related_name='books',
                                 verbose_name='категория')
    authors = models.ManyToManyField(Author, related_name='books', verbose_name='авторы')
    languages = models.ManyToManyField(Language, related_name='books', verbose_name='языки')
    themes = models.ManyToManyField(Theme, related_name='books', verbose_name='темы')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='дата создания')
    updated_at = models.DateTimeField(auto_now=True, verbose_name='дата изменения')

    class Meta:
        verbose_name = 'Книга'
        verbose_name_plural = 'Книги'

    def __str__(self):
        return f'{self.name} - {self.isbn}'

deals/models.py
from django.db import models

# Create your models here.

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class Country(models.Model):

    name = models.CharField(max_length=160, verbose_name='название')

    class Meta:
        verbose_name = 'Страна'
        verbose_name_plural = 'Страны'

    def __str__(self):
        return self.name


class Region(models.Model):

    name = models.CharField(max_length=160, verbose_name='название')
    country = models.ForeignKey(Country,
                                on_delete=models.SET_NULL,
                                null=True,
                                verbose_name='страна',
                                related_name='regions')

    class Meta:
        verbose_name = 'Регион'
        verbose_name_plural = 'Регионы'

    def __str__(self):
        return f'{self.id} - {self.name}'


class City(models.Model):

    name = models.CharField(max_length=160, verbose_name='название')
    region = models.ForeignKey(Region,
                               on_delete=models.SET_NULL,
                               null=True,
                               verbose_name='регион',
                               related_name='cities')

    class Meta:
        verbose_name = 'Город'
        verbose_name_plural = 'Города'

    def __str__(self):
        return f'{self.id} - {self.name}'


class User(AbstractUser):

    class GenderChoice(models.TextChoices):
        MALE = 'M', 'мужской'
        FEMALE = 'F', 'женский'
        NONE = 'N', 'не указан'

    email = models.EmailField(unique=True, verbose_name='e-mail')
    birthday = models.DateField(blank=True, verbose_name='день рождения')
    gender = models.CharField(max_length=1,
                              choices=GenderChoice.choices,
                              default=GenderChoice.NONE,
                              verbose_name='пол')
    date_updated = models.DateTimeField(auto_now=True, verbose_name='дата изменения')
    city = models.ForeignKey(City,
                             on_delete=models.SET_NULL,
                             null=True,
                             verbose_name='город',
                             related_name='users')
    avatar = models.ImageField(upload_to='users_avatars', verbose_name='аватар')

    class Meta:
        verbose_name = 'Пользователь'
        verbose_name_plural = 'Пользователи'

    def __str__(self):
        return self.username


class Contact(models.Model):

    class ContactsChoice(models.TextChoices):
        EMAIL = 'EM', 'E-mail'
        PHONE = 'PH', 'Телефон'
        VK = 'VK', 'ВКонтакте'
        GOOGLE = 'GL', 'Google'

    name = models.CharField(max_length=2,
                            choices=ContactsChoice.choices,
                            default=ContactsChoice.EMAIL,
                            verbose_name='название')
    info = models.CharField(max_length=160, verbose_name='информация')
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='пользователь', related_name='contacts')
    date_created = models.DateField(auto_now_add=True, verbose_name='дата создания')
    date_updated = models.DateTimeField(auto_now=True, verbose_name='дата изменения')

    class Meta:
        verbose_name = 'Контакт'
        verbose_name_plural = 'Контакты'

    def __str__(self):
        return f'{self.id} - {self.name}'

books/views.py
from django.shortcuts import render
from books.models import Book, Category
from django.views.generic.list import ListView


def index(request):
    return render(request, 'books/index.html')


def book_page(request):
    return render(request, 'books/book-page.html')


class CatalogListView(ListView):
    model = Book
    template_name = 'books/catalog.html'
    extra_context = {
        'title': 'Booksharing - Каталог книг',
        'categories': Category.objects.all()
    }

    def get_queryset(self):
        category_id = self.kwargs.get('category_id')
        return Book.objects.select_related('category').prefetch_related('authors').all() if not category_id \
            else Book.objects.select_related('category').prefetch_related('authors').filter(category_id=category_id)

deals/views.py
from django.shortcuts import render

# Create your views here.

users/views.py
from django.shortcuts import render

# Create your views here.

books/templates/books/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Booksharing</title>
    <link rel="stylesheet" href="{% static 'styles/main_style.css' %}">
    {% block page_css %} {% endblock %}
</head>

<body>
    <div class="header header_and_footer">
        <div class="menu header_elements">
            <a class="menu_point" href="{% url 'index' %}">Главная</a>
            <a class="menu_point" href="{% url 'books:index' %}">Каталог книг</a>
        </div>
        <div class="authorization header_elements">
            <a class="auth_point" href="#"><img src="{% static 'img/account_box.svg' %}" alt=""
                    class="user_box">Зарегистрироваться</a>
            <a class="auth_point" href="#"><img src="{% static 'img/account_circle.svg' %}" alt="" class="user_box">Войти</a>
        </div>
    </div>
    {% block page_content %} {% endblock %}
    <div class="footer header_and_footer">
        <p class="copyright">© HelenMaksimova 2021</p>
    </div>
</body>

</html>

books/templates/books/book-page.html
{% extends 'books/base.html' %}
{% load static %}

{% block page_css %}
    <link rel="stylesheet" href="{% static 'styles/book_page_style.css' %}">
{% endblock %}

{% block page_content %}
    <div class="main">
        <div class="book_sheet" id="book_info">
            <h3 class="book_title">Русалочка</h3>
            <h4 class="book_author">Ганс Христиан Андерсен</h4>
            <div class="book_info_container">
                <img class="book_img" src="./img_books/07.jpg" alt="">
                <p class="book_description">
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit.
                    Etiam consectetur lobortis dui, et iaculis mi ultrices vitae.
                    Donec posuere finibus ultrices.
                    Quisque lectus dui, blandit non lorem ut, auctor vestibulum arcu.
                    Nam eget nisi a massa tincidunt aliquam.
                </p>
            </div>
            <div class="book_details">
                <p class="book_characteristic">ISBN:</p>
                <p class="book_characteristic">Год издания:</p>
                <p class="book_characteristic">Издательство:</p>
                <p class="book_characteristic">Количество страниц:</p>
                <p class="book_characteristic">Язык:</p>
                <p class="book_characteristic">Категория:</p>
                <p class="book_characteristic">Темы:</p>
            </div>
        </div>
        <div class="book_sheet" id="book_deals"></div>
        <div class="book_sheet" id="book_dealer_info"></div>
    </div>
{% endblock %}

books/templates/books/catalog.html
{% extends 'books/base.html' %}
{% load static %}

{% block page_css %}
    <link rel="stylesheet" href="{% static 'styles/catalog_style.css' %}">
{% endblock %}

{% block page_content %}
    <div class="main">
            <div class="catalog_menu">
                <a href="{% url 'books:index' %}">
                    <h3 class="catalog_category">Все книги</h3>
                </a>
                {% for category in categories %}
                <a href="{% url 'books:category_filter' category.id %}">
                    <h3 class="catalog_category">{{ category.name }}</h3>
                </a>
                {% endfor %}
            </div>
            <div class="catalog_content">
                {% for book in object_list %}
                <div class="catalog_card">
                    <a href="{% url 'books:book' %}">
                        <h3 class="card_title">{{ book.name }}</h3>
                    </a>
                    <h4 class="card_author">{% for author in book.authors.all %} {{ author }} <br> {% endfor %}</h4>
                    <img src="{{ book.image.url }}" class="card_image">
                    <p class="card_count">Книг в наличии: {{ book.books_count }}</p>
                    <p class="card_cities">В городах:</p>
                </div>
                {% endfor %}
            </div>
        </div>
{% endblock %}

books/templates/books/index.html
{% extends 'books/base.html' %}
{% load static %}

{% block page_css %}
    <link rel="stylesheet" href="{% static 'styles/index_style.css' %}">
{% endblock %}

{% block page_content %}
    <div class="main">
        <div class="title">
            BOOKSHARING
        </div>
        <div class="slogan_title">
            Подарите ненужным книгам новую жизнь!
        </div>
        <div class="slogan_text">
            Lorem ipsum dolor sit amet, consectetur adipiscing elit.
            Etiam consectetur lobortis dui, et iaculis mi ultrices vitae.
            Donec posuere finibus ultrices.
            Quisque lectus dui, blandit non lorem ut, auctor vestibulum arcu.
            Nam eget nisi a massa tincidunt aliquam.
        </div>
    </div>
{% endblock %}